---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---


```{r}
# library imports
library(tidyverse)
```

### Import Data
```{r}
df <- read.csv('/Volumes/GoogleDrive/My Drive/Yevashan Perumal MSc v2/Data/data with some cdw.csv')
```

```{r}
head(df)
```

```{r}
dim(df)
```


Drop the unnecessary columns
```{r}
cols_to_drop <- c('RecordID','ProductCode','DimGCSPartyKeyLifeCovered'
                  ,'DimDateKeyInitiated','DimDateKeyFinalised','DimDateKeyAccepted'
                  ,'UnderwritingInitiationDate','UnderwritingFinaliseDate')

#drop columns
df2 <- df %>% select(-all_of(cols_to_drop))

#remove duplicate rows
df2 <- df2 %>% distinct()

dim(df2)
```
```{r}
head(df2)
```
```{r}
str(df2)
```
<<<<<<< HEAD


```{r}
tab1 <- df2 %>% summarise_all(n_distinct)%>%t()
tab1 <- data.frame(tab1)
tab1 %>% arrange(tab1)
```
# Univariate exploration
=======
>>>>>>> f2a211743399f24ba4c478ae65bc84206ff00178

## Numeric Variables (and ones that should be)

```{r}
tab1 <- df2 %>% summarise_all(n_distinct)%>%t()
tab1 <- data.frame(tab1)
tab1 %>% arrange(tab1)
```


```{r}
df2$GammaGTValue <-  as.integer(df2$GammaGTValue)
df2 %>% filter(GammaGTValue<200) %>%  ggplot(aes(x=GammaGTValue))+geom_histogram(binwidth = 10)
```
Some really weird large outliers than need to be taken care of.
Also some NAs introduced when converting to character.


```{r}
cols_to_drop2 <- c()
```

```{r}
df2
```



# Target Variable
```{r}
df2$GammaGTValue <-  as.integer(df2$GammaGTValue)
df2 %>% filter(GammaGTValue<200) %>%  ggplot(aes(x=GammaGTValue))+geom_histogram(binwidth = 10)
```

